services:
  # Serviço Web - Interface do Chatbot
  chatbot:
    build: .
    container_name: ia-local-web
    network_mode: host
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - MODEL_NAME=llama2
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    volumes:
      # Volumes para desenvolvimento - código atualizado sem rebuild
      - ./app.py:/app/app.py
      - ./pdf_processor.py:/app/pdf_processor.py
      - ./templates:/app/templates
      - ./static:/app/static
      - ./test_pdf.py:/app/test_pdf.py
      # Volumes para dados persistentes
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped
    # Configuração para desenvolvimento
    command: python app.py

volumes:
  ollama_data:
    driver: local 