version: '3.8'

services:
  # Serviço Ollama - Modelo de IA
  ollama:
    image: ollama/ollama:latest
    container_name: ia-local-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  # Serviço Web - Interface do Chatbot
  chatbot:
    build: .
    container_name: ia-local-web
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL_NAME=llama2
    volumes:
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local 